### ISSUE TITLE
Missing implementation for Label?

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#104]
In the interface, I do see a `Label` node that is the target for `goto` statements. But I do not see any implementation or factory function for that node.

**Comment by GorNishanov** [comment]
Do we need Label node at all? The comment in a labeled statement says:

```
                                // -- Labeled_stmt --
   // This node is for labeled-statement:
   //   - identifier : statement
   //   - case constant-expression : statement
   //   - default : statement
   // IPR represents that "label()" as an expressions so that it can
   // handle "identifier", "case cst-expr" and "default", where cst-expr
   // is an arbitrary constant-expression.
```

In this model, label does not need a dedicated node at all. It is just an identifier (though after the recent change to move names hierarchy out of the Expr tree, it is probably need to be Id_expr with a location)

**Comment by Xazax-hun** [comment]
I see that makes sense. In that case, does it make sense to have a `Label` interface node at all?

I also have several questions about the `Labeled_stmt` node.
- What does that statement represent? Is it the next statement that we would jump to? While I do see that the C++ grammar requires the label to be followed by a statement, I would assume that the next statement would be obvious from the context without storing it explicitly. Is this a residue from reading the grammar or is it useful information and I am missing something?
- For me, it is not clear from the documentation how to represent `default`, since that is not an identifier, but a keyword.
- How to distinguish between `case constant-expression:` and `identifier:`?

Consider the following (maybe, clang accepts it) valid code:
```
enum A { test };

void f(int a) {
goto test;
test:
{}
}
```

As far as I understand, the `label()` method would return the `test` identifier both for `test:` and `case test:`. But their semantics are rather different.

**Comment by GorNishanov** [comment]
Labels are never on their own. Labeled statement is a statement with a label. 

From c++ grammar:
```
labeled-statement:
   attribute-specifier-seq-opt identifier : statement
   attribute-specifier-seq-opt case constant-expression : statement
   attribute-specifier-seq-opt default : statement
```
When Name was an Expr, you could distinguish between an identifier which is a Name and an expression, which is probably Classic_expr.

With Name moved out of Expr hierarchy, I think we would need a label expression, so that it is distinguished from any other expression.

**Comment by Xazax-hun** [comment]
I see the point with the grammar, I am just not sure whether we should follow it. I.e. it is the compiler's job to enforce that a statement follows each label. But in case it is easy to get the next statement from the context (parent compound statement), I wonder if there is value storing a reference to it.

I am not opposed to having this link, it is definitely a nice convenience feature, I was just surprised as I thought IPR wants to be more minimal.
