### ISSUE TITLE
Link to the white paper is dead

### ISSUE THREAD

**Issue by JordanMaples** [GabrielDosReis/ipr#11]
The link ["A Principled, Complete, and Efficient Representation of C++"](http://www.axiomatics.org/~gdr/ipr/mcs.pdf) isn't accessible anymore. Is the paper hosted elsewhere?

**Comment by jghickman** [comment]
http://www.stroustrup.com/macis09.pdf

**Comment by GabrielDosReis** [comment]
Resolved.
