### ISSUE TITLE
Audit use of verb vs noun as node class names

### ISSUE THREAD

**Issue by GabrielDosReis** [GabrielDosReis/ipr#115]
@nostracodus remarked in the review of PR #112 that there were discrepancies in the uses of noun vs verb as node class names. Friendly ask on Cody to help with audit :-)

**Comment by Nostracodus** [comment]
I have a fork [here](https://github.com/Nostracodus/ipr) with changes to address issues that exist now. I am waiting until `Pretend` is added in an imminent PR before submitting changes.

**Comment by GabrielDosReis** [comment]
@Nostracodus  - Is there a good way in GitHub infra for me to see the renaming other than cloning and running a diff?

**Comment by Nostracodus** [comment]
Does [this link](https://github.com/GabrielDosReis/ipr/compare/master...Nostracodus:master) do the trick?

**Comment by GabrielDosReis** [comment]
Perfect.  Thank you!  That looks great.
Can we separate the cast from the renaming, though?

**Comment by Nostracodus** [comment]
I had a feeling you'd say that! The casting is in another commit that I don't intend to submit for PR, but I wasn't savvy enough to figure out how to provide a diff that excluded it 😂

**Comment by GabrielDosReis** [comment]
@Nostracodus  - I think the other implicit conversion node patch has been checked in; would you be able to submit this PR?

**Comment by Nostracodus** [comment]
I've published pull request #131. I think there is still an outstanding PR to add `Pretend`, which is usually a verb or an adjective ("He pretended to have friends" and "I only have pretend friends"). I guess we could nominalize that into `Pretending` in the future, but there may be other forms that work better (maybe `Pretense` or `Pretender` . . . ). None sound quite as nice as `Pretend`, though.

**Comment by GabrielDosReis** [comment]
`Pretending` comes close, as does `Pretense` - but you're right `Pretend` sounds nice :-)

**Comment by GabrielDosReis** [comment]
Fixed by #131
