### ISSUE TITLE
How to represent Base_type expansion

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#139]
Consider:

```c++
template <typename... T>
struct X : T... {};
```
This is not representable in IPR at the moment.
`Expansion` operates on Classic expressions. `Base_type` is a declaration and bases are `Sequence<Base_type>`.

This issue will interplay with #65

**Comment by GorNishanov** [comment]
This would be possible if Expansion would take an Expr as an operand.
At the moment, it is limited to just Classic expressions. As_type is not a Classic expression

**Comment by GabrielDosReis** [comment]
> This would be possible if Expansion would take an Expr as an operand.

The [definition](https://github.com/GabrielDosReis/ipr/blob/6194f1222aa193b07c19220139ee173c2240ce86/include/ipr/interface#L1325) of `Expansion` says that it is a `Classic` unary structure that takes a general `Expr` as operand.

```
   struct Expansion : Unary<Category<Category_code::Expansion, Classic>> { };
```

The factory function [`make_expansion()`](https://github.com/GabrielDosReis/ipr/blob/6194f1222aa193b07c19220139ee173c2240ce86/include/ipr/impl#L1204) takes a `const ipr::Expr&`

Am I reading that wrong?

**Comment by GorNishanov** [comment]
Yes. You are right. I was reading the definition wrong :-)
