### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#146]
I think the current README does not capture some key aspects of IPR:
* IPR is an interface first, and this repository contains the interface and a reference implementation. The separations between the two is crucial, people are free to swap the reference implementation out.
* Some notes what IPR is and what IPR is not. E.g. IPR is really just a representation and it will never provide additional facilities like a file manager. 
* IPR is an expression based language that is designed to be the superset of C++
* IPR cannot represent C++ syntax, and this is by design

Clarifying these points (any maybe some more) could help to set the expectations of potential users and avoid the community to propose contributions that are not aligned with the vision of IPR.

**Comment by GabrielDosReis** [comment]
A good chunk of these points is covered in the IPR paper, and in the interface source file.  Also, at this point I don't want the README to be a narrow edict of what is in the scope of ideas of contribute.  Furthermore, we are not being overrun by ideas clearly out of scope.  I am happy to add clarifications as we go and we get more and more of clearly out of the out-of-scope ideas.

We can revisit when things get out of hand.
