### ISSUE TITLE
Classic::implementation() make it Optional<Expr> to accomodate Overload

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#20]
For a Classic operation, say, Plus, implementation may need to store an Overload, to remember what was found during first phase lookup for a dependent expression. Something like:

```cpp
enum class S {};
int operator+(S,long) { return 42; }

template <typename T> int f(T x) { return x + 1; } 

int operator+(S,int) { return 43; }

int main() { return f(S{}); }
```

It represent x + 1, implementation() of Plus should store the Overload set containing `operator+(S, long);` function.

In the following fragment, 's + 1' is fully resolved during first phase lookup and thus will store Declfunc `operator+(S, long)`.

```cpp
enum class S {};
int operator+(S,long) { return 42; }

template <typename T> int f(T x) { return S{} + 1; }

int operator+(S,int) { return 43; }

int main() { return f(S{}); }
```

**Comment by GabrielDosReis** [comment]
In short, what we have here is that the resolution of the implementation can be 0 (when in a templated context where no declaration is visible), 1 (where there is exactly on implementation, the majority of cases), or many (in a templated context where overload resolution has to be postponed).

**Comment by GabrielDosReis** [comment]
Fixed.
