### ISSUE TITLE
Compile error in linux

### ISSUE THREAD

**Issue by Joilnen** [GabrielDosReis/ipr#206]
I got this error when try to compile, can't "grep" SIGSTKSZ defined in any place  

 54%] Built target ipr
[ 63%] Building CXX object tests/unit-tests/CMakeFiles/unittests.dir/main.cpp.o
In file included from /home/joilnen/cpp_devel/ipr/tests/unit-tests/main.cpp:2:
/home/joilnen/cpp_devel/ipr/3rdparty/doctest/doctest.h:4032:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4032 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
make[2]: *** [tests/unit-tests/CMakeFiles/unittests.dir/build.make:76: tests/unit-tests/CMakeFiles/unittests.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: tests/unit-tests/CMakeFiles/unittests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by GabrielDosReis** [comment]
`SIGSTKSZ` is a macro supposed to be provided by the header `<signal.h>` on your system.  Which linux system is this?  Do you have the build and development packages installed?

Note: all PRs are tested against ubuntu-20.4 in the CI.

**Comment by GabrielDosReis** [comment]
Closing as likely incomplete development environment setup.  Please reopen if new information surfaces, with more details about the setup environment.
