### ISSUE TITLE
How to represent function declaration?

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#21]
Funcdecl uses Mapping to store parameters.
Mapping must have the body.

How to represent:

int f(int x);

The workaround I used is to make Mapping result to be optional. Thus, the declaration of the function will be a Fundecl with initializer to be a mapping with empty body

**Comment by GabrielDosReis** [comment]
Once choice is to have `Fundecl` have its own set of parameters, keeping `Mapping` as the initializer.  Alternatively, as done with classes, go with the principle that a function exists independently of how it is named.  Both approaches have different downsides and tradeoffs.
