### ISSUE TITLE
Handler should decide whether it is Binary<Parameter, Block> or Binary<Var, Block>

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#23]
Currently it is Handler<Decl,Block>.
With the current C++, the only things that can fit the Decl is either a Parameter or Var. 
Unless there is some evolution path where C++ may acquire other kinds of catch clauses, we should narrow the IPR for Handler to either have a Parameter or a Var as a first operand.

**Comment by GabrielDosReis** [comment]
A catch block is a form of functional abstraction, where the parameter is (dynamically) initialized by the exception being handled.  So, it is more like a `Parameter` than a `Var`.  And of course, a function parameter is a local variable too.
