### ISSUE TITLE
"this" in member variable initializer

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#28]
```
struct X{
    int x;
    int y = this->x;
};
```
Normally, in a member function, this is an Id_expr resolved to implicit function parameter "this".
Would in the case above, "this" will be an Id_expr("this") without resolution?

**Comment by GabrielDosReis** [comment]
Yes, the `this` here in a default member initializer has meaning only in the context of the constructor that uses it.
