### ISSUE TITLE
Literal and other expr should ne unique

### ISSUE THREAD

**Issue by d-winsor** [GabrielDosReis/ipr#32]
ipr::Literal
ipr::Sizeof
ipr::Typeid

Should all be in stable_farm to allow them have unique locations once they are added to expressions. If internalization of literals is desired consider implementing both a ipr::Literal and ipr::Literal_expr node.

**Comment by GabrielDosReis** [comment]
There is a need to separate  _core value expression_ hierarchy from _expression with location_ hierarchy.

**Comment by Xazax-hun** [comment]
Do you mean value categories? Like lvalues and rvalues?
