### ISSUE TITLE
Should Empty_stmt really use a phantom as it child.

### ISSUE THREAD

**Issue by d-winsor** [GabrielDosReis/ipr#34]
ipr::Phantom has a clear role in determining the unknown bound of an array. Should it really be reused for Empty_stmt's child. This may confuse user who are explicitly visiting phantoms for their intended purpose.

I suggest the addition of a new expr node.

**Comment by GabrielDosReis** [comment]
Node visitation should always a context -- it is as part of a type, statement, etc?  A phantom node having  a statement as immediate context can mean only one thing, which is different from a phantom with a type as immediate context.

**Comment by GabrielDosReis** [comment]
The use of `Phantom` as expression in an `Empty_stmt` is correct.  Traversals should always have a local idea of how they got to a particular node.
