### ISSUE TITLE
Implict_cast is missing

### ISSUE THREAD

**Issue by d-winsor** [GabrielDosReis/ipr#36]
No construct in IPR for implicit casts such as lvalue-to-rvalue conversions or array to pointer decay.

**Comment by GabrielDosReis** [comment]
Agreed that it is useful to represent certain steps of the full semantics elaboration such as coercions, promotions, etc.

**Comment by GabrielDosReis** [comment]
@d-winsor - is this issue resolved by your PRs?  What else is left?

**Comment by GabrielDosReis** [comment]
This is now fixed by age various PRs to add implicit conversions
