### ISSUE TITLE
Multiple build systems

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#45]
Currently there are both `CMake` files and `autoconf` build systems.
Is the project expected to continue to maintain both build systems? 
Since probably CMake is the most widespread in the C++ community, getting rid of `autoconf` would probably make the repo cleaner, and easier to interpret for the newcomers.

**Comment by GabrielDosReis** [comment]
The future is to remove the Autotools build system, now that we've fully migrated to CMake.

**Comment by Xazax-hun** [comment]
Great news, thanks!

**Comment by GabrielDosReis** [comment]
Fixed by https://github.com/GabrielDosReis/ipr/commit/1c263904e2e41edb3f166659b533d089fd95024a
