### ISSUE TITLE
Should "owner()" be generating_map() in comment about Decl?

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#5]
https://github.com/GabrielDosReis/ipr/blob/3fc82cb0a38932b82f06a2efda4087ddad61fa84/include/ipr/interface#L1813

   // We take the view that all declarations can be parameterized.
   // Therefore, declaration nodes potentially are instantiations of a
   // a template given by "pattern()", with a set of template-arguments,
   // given by "substitutions()".  A declaration for which we have
   // an empty substitutions() is either

whereas in the code we have:

```
      virtual const Named_map& generating_map() const = 0;
      virtual const Sequence<Substitution>& substitutions() const = 0;
```

**Comment by GabrielDosReis** [comment]
`generating_map()`, `substitutions()`, and `owner()` are no longer part of the interface.  
Closing as issue no longer relevant to current code base.
