### ISSUE TITLE
Remove Type_id and Base_type

### ISSUE THREAD

**Issue by GabrielDosReis** [GabrielDosReis/ipr#65]
Find a different unifying representation of base-class subobjects

**Comment by GorNishanov** [comment]
Will impact #139

**Comment by GabrielDosReis** [comment]
> Will impact https://github.com/GabrielDosReis/ipr/issues/139 (possibly in a positive way)

As discussed in #139 , expansion of base class pack is already representable and the resolution of this issue has no bearing on that.

**Comment by GabrielDosReis** [comment]
`Type_id` is being retained as a mean to name non-constructor conversion functions.
