### ISSUE TITLE
Missing representation for <attributes-seq> <empty-declaration> 

### ISSUE THREAD

**Issue by GorNishanov** [GabrielDosReis/ipr#7]

**Comment by GabrielDosReis** [comment]
An empty-declaration does not meet the IPR basic model of declaration: a name, a type, and an optional initializer.  This construct is more like a meta computation over a region than an actual declaration.

**Comment by GabrielDosReis** [comment]
@GorNishanov  - Is there actually a case where an _attribute-specifier-seq_ is applied to an _empty-declaration_?  I looked through the ISO C++ grammar and I was unable to find a place where that occurs...  Any example?

**Comment by GorNishanov** [comment]
Nearly. In the grammar, it is a distinct `attribute-declaration`.

```
declaration:
    empty-declaration
    attribute-declaration

empty-declaration:
     ;

attribute-declaration:
     attribute-specifier-seq ;
```

I think that now with the Region acquiring a `sequence<Expr>` it is representable.

```c++
struct S
{
   [[some-attr]] ; // This now an empty statement which has an attribute and now can be added into a Sequence of exprs.
   int z;
};
```

**Comment by GabrielDosReis** [comment]
> Nearly. In the grammar, it is a distinct _attribute-declaration_.

Ah! I missed that one.  Thanks!

> I think that now with the Region acquiring a `Sequence<Expr>` it is representable.

I agree.

Closing as resolved.
