### ISSUE TITLE
Typedecl::membership() should be optional because of 'local classes'

### ISSUE THREAD

**Issue by d-winsor** [GabrielDosReis/ipr#70]
Typedecl will not have a membership if it is declared locally in a function.
```cpp
int foo()
{
    struct Local { int x; };
}
```

**Comment by GabrielDosReis** [comment]
It should instead return a `const Expr&` instead of `const Type&`: in the above case we want to designate `foo` as its owner, or the nested block if the definition appears in deeper.  Alternatively, it could just systematically return `const Region&`.

**Comment by d-winsor** [comment]
Would the owner be ipr::Fundecl (foo) or the ipr::Block. Consider the case below:

```cpp
void foo()
{
    {
        struct SameName{ int blue; };
    }
    {
        struct SameName{ int red; };
    }
}
```

**Comment by GabrielDosReis** [comment]
Yes, that is exactly why I suggested `foo`, or the enclosing block if nested.  `foo` is for the case where it is the outermost compound statement that makes up the body of the function -- so no indirection is needed to find the function that owns the block that owns the type.

**Comment by d-winsor** [comment]
Sorry I just miss read your reply,
