### ISSUE TITLE
Overloadable operators

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#83]
For me, the name `Classic` is very confusing for that class, since all the added functionality is related to overloading. I'd prefer something like `Overloadable_operator`. Also, it is not clear to me from the documentation what the `implementation` is. Is it a function body? Is it a function declaration? Something else? The `Expr` class is almost at the top of the inheritance hierarchy and it gives the user little clue what is the idiomatic way to build IPR. While I appreciate the flexibility of the format, I think adding a bit more constraints might help potential users a lot to intuitively understand how they supposed to use IPR.

**Comment by GabrielDosReis** [comment]
The IPR does not aim to represent exactly ISO C++, mimicking its barnacle.  Rather, it is designed to represent a more regular language that happens to contain C++ -- which is thought of as the "classic" language.  All C++ operators are potentially overloadable, so the suggest name does capture the intent.  I will retain that name for now.

The `implementation` field -- when not null -- refers to a user-supplied declaration (which can be a definition) in case the operator is effectively overloaded.  The `Expr` class is not your conventional C++ expression hierarchy class.  It is the root of IRP expressions.

**Comment by Xazax-hun** [comment]
> The `implementation` field -- when not null -- refers to a user-supplied declaration

Does that mean I am free to change it to `Decl` from `Expr` or is it intentional to use the root class?

**Comment by GabrielDosReis** [comment]
> Does that mean I am free to change it to Decl from Expr or is it intentional to use the root class?

No, that would be undoing an intentional change that fixed a bug.  In a templated context, the `implementation` field can refer to an overload set, which is an expression.

**Comment by Xazax-hun** [comment]
I see this makes sense. I think this warrants a comment in `interface`. I will open a PR clarifying this.

**Comment by Xazax-hun** [comment]
Opened PR: https://github.com/GabrielDosReis/ipr/pull/84
