### ISSUE TITLE
Types of While, Break, Continue, etc

### ISSUE THREAD

**Issue by Xazax-hun** [GabrielDosReis/ipr#87]
In IPR everything has a type. I have hard time wrapping my head around, what the types of certain statements supposed to represent.

One example:
The type of `While` is the type of the second argument, which is the body. I have trouble understanding how to make sense of this, for the following reasons:
- If we think of an expression based language, the last thing we evaluate before exiting from a while statement would be the condition, so in this case I would expect the type of while to be the condition. 
- The type of `Break` is the type of the "from" property. So in case the body of a `While` is a `Break`, we have a circular dependency.
- The current structure of IPR makes it really challenging to handle `Break` and `Continue` statements. For example, `While` needs to be created after the body is done, since factory function for `While` expects the body. So we will construct `Break` and `Continue` first, even before `While` was created. As a result, we cannot fill the `from` property of a `Break` right away. The problem is, as soon as some code tries to fetch the type of `Break`, it will crash, since the property is not filled yet. As a result, we need to be very careful not to read the `type` property of `Break` until we finished creating the corresponding `While`. This makes it hard to reason about, or even inspect IPR locally, while it is under construction.

For me, it would be more natural to make `Break` and `Continue` void types (in case one want the type of the `from`, they can still access it like `from()->type()`), make statements like `While` to inherit the type of the last evaluated expression.

Of course, I might just misunderstand the language IPR wants to define.

**Comment by Xazax-hun** [comment]
On the second thought, it is a dynamic property what evaluated last in a `While` loop, as with a `Break` we can skip the `cond`. so with a multi-exit loop one would need a flow sensitive type checker to determine a type for the loop. Hardcoding any of the choices in the API feels arbitrary for me. But again, I might be totally wrong and the meaning of the type here might be something completely different from the type of the last evaluated expression.

**Comment by GabrielDosReis** [comment]
`break` and `continue` -- as expressions -- don't yield any value, so any IPR node builder assigning a `void` type to such expression is fine.  I don't expect that type assignment to be done by the IPR interface itself.  

Is the flexibility the issue?

**Comment by Xazax-hun** [comment]
I opened a PR to deatch the type of break/continue from the loops, this way it is possible to assign `void` type to them. I believe this resolves the issues I have.
